### ISSUE TITLE
Resize and crop

### ISSUE THREAD

**Issue by samuelcarreira** [samcpt/webPGUI#1]
Implement these options

**Comment by samuelcarreira** [comment]
Resize option added (with very simple interface)

**Comment by sylphrena0** [comment]
Would be great to be able to resize and maintain aspect ratio automatically (as in, enter height or width and have it resize the other dimension to the same aspect ratio as before)

**Comment by samuelcarreira** [comment]
Sorry this app is deprecated and no further development will be done
