### ISSUE TITLE
Save log file as text

### ISSUE THREAD

**Issue by xan2622** [samcpt/webPGUI#10]
Could you please add an option to save the log as a .txt file ?

Maybe a button on the Output Log window ?

<img width="452" alt="webpGUI_outputLog" src="https://user-images.githubusercontent.com/1732773/69492133-a7240a00-0e9e-11ea-8360-0882b282db2c.PNG">

Thank you.

**Comment by samuelcarreira** [comment]
Sorry this app is deprecated and no further development will be done
