### ISSUE TITLE
File not found error when downloading program from OrangeDox

### ISSUE THREAD

**Issue by finn-e** [samcpt/webPGUI#11]
I'm getting an error "File Not Found" when trying to download using the link in the readme, to OrangeDox.
Please update the link and it would be great if you used github releases so we don't have to go thru another site.

**Comment by DaRealNOX** [comment]
Same here. Annoying that I now have to quickly put together a GUI for batch jobs myself, even though someone else has already completed one. :'(

@samuelcarreira Is there any chance you'll revive webPGUI?

**Comment by samuelcarreira** [comment]
Hi, please check the releases

https://github.com/samuelcarreira/webPGUI/releases

Thanks for the interest but there's no plans to continue to support this project

**Comment by DaRealNOX** [comment]
Thanks for rehosting! 👍
