### ISSUE TITLE
Hidden button

### ISSUE THREAD

**Issue by xan2622** [samcpt/webPGUI#8]
On the **Input Image** tab, there is a hidden button (on the right). 
I guess it is just misplaced but what does it do? 

<img width="579" alt="Capture02" src="https://user-images.githubusercontent.com/1732773/69483543-c5e7b980-0e28-11ea-9600-9dac876fe755.PNG">

**Comment by samuelcarreira** [comment]
Sorry this app is deprecated and no further development will be done
