### ISSUE TITLE
Broken link for the codec

### ISSUE THREAD

**Issue by xan2622** [samcpt/webPGUI#9]
I have noticed that on the https://github.com/samuelcarreira/webPGUI page, the link for the codec is broken (the target page has vanished).

> How to view webP images?
> 
> Google Chrome can open WebP files natively. Or install Windows CODEC https://developers.google.com/speed/webp/docs/webp_codec if you want to view WebP files in Windows Photo Viewer and their thumbnails in Windows Explorer

I could find the missing page with WayBack Machine: 
https://web.archive.org/web/20170426101156/https://developers.google.com/speed/webp/docs/webp_codec

Windows 10 natively displays webp thumbnails in Explorer (at least for me, could you confirm that you can also view webp thumbnails in explorer? thanks).

Or, to be able to view these images, the user can use [vwebp](https://developers.google.com/speed/webp/docs/vwebp) or [Krita](https://krita.org)

**Comment by samuelcarreira** [comment]
Sorry this app is deprecated and no further development will be done
